name: Go Module CI/CD

on:
  push:
    tags:
      - 'v*'   # Run only when version tags are pushed (e.g., v0.1.0, v1.0.0)

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # or your preferred version

      - name: Verify build
        run: go build ./...

      - name: Run tests
        run: go test -v ./...

  publish:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Trigger pkg.go.dev refresh
        run: |
          curl "https://proxy.golang.org/github.com/cocoonmail/cocoonmail-go/@v/${GITHUB_REF_NAME}.info"
